name: scope
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - pyarrow
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - plotly
  - streamlit
  - jupyterlab
  - ipykernel
  - pymongo
